version: "2"

linters:
  default: all
  disable:
    - depguard
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - misspell
    - noinlineerr
    - varnamelen
    - wsl

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - errcheck
          - exhaustruct
          - funlen
          - gocognit
          - gosec
          - paralleltest
          - testpackage

  settings:
    cyclop:
      max-complexity: 11

    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '.+/cobra\.CompletionOptions$'
    gosec:
      excludes:
        - G101
        - G304

formatters:
  enable:
    - gofmt
    - golines
