version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - lll
    - mnd
    - nlreturn
    - noinlineerr
    - varnamelen
    - wsl
    - wsl_v5

  exclusions:
    rules:
      - path: cmd/
        linters:
          - gochecknoinits
      - path: internal/helper/ui/ansi/ansi.go
        linters:
          - godoclint
      - path: internal/helper/ui/input/input.go
        linters:
          - errcheck
          - gosec
      - path: _test\.go
        linters:
          - errcheck
          - funlen
          - gosec
          - maintidx
          - paralleltest
          - testpackage
      - path: internal/helper/ui/progress/progress.go
        text: "the symbol (Kbps|Mbps|Gbps)"
        linters:
          - revive

  settings:
    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '.+/cobra\.CompletionOptions$'

    funcorder:
      alphabetical: true

    gocritic:
      enable-all: true
      disabled-checks:
        - paramTypeCombine
        - unnamedResult

    gosec:
      excludes:
        - G101
        - G304
        - G602

    govet:
      enable-all: true
      disable:
        - shadow

    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allow-strs: '"","/","-","%w","%w: %w"'
              allow-ints: "0,1,100"
              allow-floats: "0.0"
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: deep-exit
          disabled: true
        - name: enforce-map-style
          arguments:
            - "make"
        - name: enforce-slice-style
          arguments:
            - "make"
        - name: enforce-repeated-arg-type-style
          arguments:
            - func-arg-style: "full"
              func-ret-val-style: "full"
        - name: increment-decrement
        - name: inefficient-map-lookup
        - name: line-length-limit
          disabled: true
        - name: package-directory-mismatch
        - name: unnecessary-if
        - name: unexported-naming
        - name: unhandled-error
          arguments:
            - "^fmt.Print"
            - "^fmt.Printf"
            - "^fmt.Println"
        - name: unnecessary-format
        - name: useless-fallthrough

    unconvert:
      fast-math: true
      safe: true

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      module-path: switchtube-downloader
