version: "2"

linters:
  default: all
  disable:
    - arangolint
    - depguard
    - dupword
    - forbidigo
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goheader
    - goprintffuncname
    - grouper
    - lll
    - misspell
    - noinlineerr
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - unqueryvet
    - varnamelen
    - wsl
    - zerologlint

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - errcheck
          - exhaustruct
          - funlen
          - gocognit
          - gosec
          - maintidx
          - paralleltest
          - testpackage

  settings:
    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '.+/cobra\.CompletionOptions$'
    funcorder:
      alphabetical: true
    gosec:
      excludes:
        - G101
        - G304

formatters:
  enable:
    - gofmt
    - golines
