version: "2"

linters:
  default: all
  disable:
    - depguard
    - forbidigo
    - lll
    - noinlineerr
    - varnamelen
    - wsl

  exclusions:
    rules:
      - path: cmd/
        linters:
          - gochecknoglobals
          - gochecknoinits
      - path: internal/helper/ui/colors.go
        linters:
          - godoclint
      - path: internal/helper/ui/input.go
        linters:
          - cyclop
          - mnd
      - path: _test\.go
        linters:
          - errcheck
          - exhaustruct
          - funlen
          - gosec
          - maintidx
          - paralleltest
          - testpackage

  settings:
    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '.+/cobra\.CompletionOptions$'
    funcorder:
      alphabetical: true
    gosec:
      excludes:
        - G101
        - G304

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      module-path: switchtube-downloader
