version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: switchtube-downloader
    ldflags:
      - -s -w -X switchtube-downloader/cmd.version={{.Tag}}

archives:
  - format: "zip"
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: niekdomi
    name: SwitchTube-Downloader

  mode: replace

changelog:
  use: github
  format: "{{.Message}}"
  sort: asc
  abbrev: -1

  groups:
    - title: "✨ Features"
      regexp: '^.*?(feat|perf)(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔧 Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "🛠️ Maintenance"
      regexp: '^.*?(build|chore|ci|refactor)(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "🧪 Tests"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "📚 Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 5

aurs:
  - name: switchtube-downloader-bin
    homepage: "https://github.com/domi413/SwitchTube-Downloader"
    description: "A lightweight CLI to download SwitchTube videos"

    maintainers:
      - "Dominik Bühler <dom.buehler@outlook.com>"

    license: "MIT"

    git_url: "ssh://aur@aur.archlinux.org/switchtube-downloader-bin.git"

    private_key: "{{ .Env.AUR_KEY }}"

    commit_author:
      name: "niekdomi"
      email: "dom.buehler@outlook.com"

    package: |-
      # Install the binary, license, and documentation
      install -Dm755 "switchtube-downloader" "$pkgdir/usr/bin/swdl"
      install -Dm644 "LICENSE" -t "$pkgdir/usr/share/licenses/$pkgname"
      install -Dm644 "README.md" -t "$pkgdir/usr/share/doc/$pkgname"

    commit_msg_template: "Update to {{ .Tag }}"
    disable: "{{ .IsSnapshot }}"
