name: CI

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install typstyle
        uses: taiki-e/install-action@v2
        with:
          tool: codebook-lsp

      - name: Check Formatting
        run: codebook-lsp lint .

  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          check-latest: true

      - name: Build
        run: go build -ldflags "-s -w -X switchtube-downloader/cmd.version=$(git describe --tags --always)"

  lint:
    runs-on: ubuntu-latest
    name: Lint
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  # NOTE: I removed the test cases since they didn't add much value.
  # test:
  #   runs-on: ubuntu-latest
  #   name: Test & Coverage
  #   timeout-minutes: 1

  #   permissions:
  #     pull-requests: write

  #   if: ${{ !github.event.pull_request.draft }}

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v6

  #     - name: Set up Go
  #       uses: actions/setup-go@v6
  #       with:
  #         go-version: "1.25"
  #         check-latest: true

  #     - name: Run tests and generate coverage
  #       run: |
  #         go test -coverprofile=coverage.out ./internal/...
  #         go tool cover -func=coverage.out > coverage.txt

  #     - name: Generate coverage report
  #       if: github.event_name == 'pull_request'
  #       run: bash .github/scripts/generate-coverage-md.sh

  #     - name: Post coverage comment
  #       if: github.event_name == 'pull_request'
  #       uses: marocchino/sticky-pull-request-comment@v2
  #       with:
  #         header: coverage-report
  #         path: coverage.md
